
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3030:3030
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: vetclinic
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      # image: postgres
      # restart: always
      # user: postgres
      # secrets:
      #   - db-password
      # volumes:
      #   - db-data:/var/lib/postgresql/data
      # environment:
      #   - POSTGRES_DB=example
      #   - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      # expose:
      #   - 3036
      # ports:
      #  - 5432:5432
      # healthcheck:
      #    test: [ "CMD", "pg_isready" ]
      #    interval: 10s
      #    timeout: 5s
      #    retries: 5
volumes:
  db:
    name: postgres_db