
services:
  # server:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3030:3030
  #   depends_on:
  #     - db
  # client:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./frontend
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #     - server
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: vetclinic
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    name: postgres_db